Added an error check for yarn as per @rhymes suggestion.

diff --git a/bin/e2e b/bin/e2e
--- a/bin/e2e
+++ b/bin/e2e
@@ -9,6 +9,11 @@ fi
 
 yarn install # ensure npm packages are up to date
 
+if [ $? -eq 1 ]; then
+   echo "Unable to launch end to end tests. An error occurred while running yarn install."
+   exit;
+fi
+
 printf "\n"
 
 read -p "Do you need to set up your end to end (E2E) testing database? Answer yes if this is your first time running E2E tests on your local machine or you need to recreate your E2E test database. (y/n) " -n 1 -r
