Update bin/knapsack_pro_cypress

diff --git a/bin/knapsack_pro_cypress b/bin/knapsack_pro_cypress
--- a/bin/knapsack_pro_cypress
+++ b/bin/knapsack_pro_cypress
@@ -1,9 +1,29 @@
-#!/bin/bash
-if [ "$KNAPSACK_PRO_TEST_SUITE_TOKEN_CYPRESS" = "" ]; then
-  KNAPSACK_PRO_ENDPOINT=https://api-disabled-for-fork.knapsackpro.com \
-    KNAPSACK_PRO_MAX_REQUEST_RETRIES=0 \
-    KNAPSACK_PRO_TEST_SUITE_TOKEN_CYPRESS=disabled-for-fork \
-    E2E=true bin/rails cypress:run_knapsack
+#!/usr/bin/env ruby
+require "cypress-rails"
+# require "pathname"
+require Pathname.new(CypressRails::Config.new.dir).join("config/environment")
+
+module CypressRails
+  class FindsBin
+    def call(dir = Dir.pwd)
+      puts "yoooooooooooooooooooooooooooooooooooooooooooooooooooo"
+      "node_modules/.bin/knapsack-pro-cypress"
+    end
+  end
+end
+
+CypressRails::FindsBin
+
+def system!(*args)
+  system(*args) || abort("\n== Command #{args} failed ==")
+end
+
+ENV["E2E"]="true"
+if !!ENV["KNAPSACK_PRO_TEST_SUITE_TOKEN_CYPRESS"]
+  CypressRails::Run.new.call
 else
-  E2E=true bin/rails cypress:run_knapsack
-fi
+  ENV["KNAPSACK_PRO_ENDPOINT"] = "https://api-disabled-for-fork.knapsackpro.com"
+  ENV["KNAPSACK_PRO_MAX_REQUEST_RETRIES"] = "0"
+  ENV["KNAPSACK_PRO_TEST_SUITE_TOKEN_CYPRESS"] = "disabled-for-fork"
+  CypressRails::Run.new.call
+end
